apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arithmetic-service
  template:
    metadata:
      labels:
        app: arithmetic-service
    spec:
      containers: 
      - name: arithmetic-service
        image: practicum15aa.azurecr.io/arithmetic-service:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: arithmetic-service
spec:
  selector:
    app: arithmetic-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000